//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VocabulatorTests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestsResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VocabulatorTests.TestsResource", typeof(TestsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;IsProcessed&quot;:false,&quot;Pronunciation&quot;:&quot;\u02C8ro\u028A.b\u0251\u02D0t&quot;,&quot;Results&quot;:[{&quot;Definition&quot;:&quot;test_definition_1&quot;,&quot;Examples&quot;:[],&quot;PartOfSpeech&quot;:&quot;test_pos&quot;},{&quot;Definition&quot;:&quot;test_definition_2&quot;,&quot;Examples&quot;:[&quot;test_example_1&quot;,&quot;test_example_2&quot;],&quot;PartOfSpeech&quot;:&quot;test_pos&quot;}],&quot;Word&quot;:&quot;test_word&quot;,&quot;IsStatusSuccess&quot;:true},{&quot;Message&quot;:&quot;test_message&quot;,&quot;IsStatusSuccess&quot;:false}].
        /// </summary>
        internal static string CollectionWithWordDtoAndErrorDtoJson {
            get {
                return ResourceManager.GetString("CollectionWithWordDtoAndErrorDtoJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{
        ///    &quot;meta&quot;: {
        ///      &quot;id&quot;: &quot;soap:1&quot;,
        ///      &quot;uuid&quot;: &quot;9ec2d3e5-5ac1-49dc-a4d2-070ba77a8e65&quot;,
        ///      &quot;src&quot;: &quot;int_dict&quot;,
        ///      &quot;section&quot;: &quot;alpha&quot;,
        ///      &quot;stems&quot;: [
        ///        &quot;soap&quot;,
        ///        &quot;soaps&quot;
        ///      ],
        ///      &quot;offensive&quot;: false
        ///    },
        ///    &quot;hom&quot;: 1,
        ///    &quot;hwi&quot;: {
        ///      &quot;hw&quot;: &quot;soap&quot;,
        ///      &quot;prs&quot;: [
        ///        {
        ///          &quot;mw&quot;: &quot;ˈsōp&quot;,
        ///          &quot;sound&quot;: {
        ///            &quot;audio&quot;: &quot;soap0001&quot;
        ///          }
        ///        }
        ///      ]
        ///    },
        ///    &quot;fl&quot;: &quot;noun&quot;,
        ///    &quot;def&quot;: [
        ///      {
        ///        &quot;sseq&quot;: [
        ///          [
        ///            [
        ///          [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string WordWithTwoDefinitionsJson {
            get {
                return ResourceManager.GetString("WordWithTwoDefinitionsJson", resourceCulture);
            }
        }
    }
}
